spring.application.name=my-claude-code
spring.ai.anthropic.api-key=tp-c14c6mm5f2qdsy4ngcpl2sw7r12exwr3x0n3n0tml4ev39md
spring.ai.anthropic.base-url=https://token-plan-cn.xiaomimimo.com/anthropic
spring.ai.anthropic.model-id=mimo-v2.5-pro

server.port=4545